const mongoose = require('mongoose');

// Only structured results are stored. The original uploaded file and its raw text are NOT saved.
const documentSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    title: { type: String, required: true, trim: true, maxlength: 200 },
    originalFileName: { type: String, default: '', maxlength: 200 },
    documentType: { type: String, default: 'other' },
    sourceType: { type: String, enum: ['file', 'camera', 'text'], default: 'text' },
    summary: { type: String, default: '' },
    importantInformation: { type: [String], default: [] },
    dates: [
      {
        _id: false,
        label: { type: String, default: '' },
        date: { type: String, default: '' }, // "YYYY-MM-DD" or "" when not clearly identified
        description: { type: String, default: '' },
      },
    ],
    requirements: { type: [String], default: [] },
    warnings: { type: [String], default: [] },
    confidence: { type: Number, min: 0, max: 100, default: 0 },
    usedFallback: { type: Boolean, default: false },
    // Tamil version of the text fields (generated by the AI in the same call), if available.
    translations: { type: mongoose.Schema.Types.Mixed, default: null },
  },
  { timestamps: { createdAt: true, updatedAt: false } }
);

documentSchema.index({ userId: 1, createdAt: -1 });

module.exports = mongoose.model('Document', documentSchema);
